<footer class="footer-3 bg-light">
            <div class="container-fluid bg-light-yellow">
                     <div class="col text-primary text-center pt-2 pb-2">
                         <ul class="list-inline pt-2 pb-2 m-0">
                         <li class="list-inline-item">
                         <a href="index.php">Book ticket</a>
                     </li ><li class="list-inline-item">
                         <a href="view_ticket.php">View/Print ticket</a>
                     </li >

                     <li class="list-inline-item">
                         <a href="cancel_ticket.php">Cancel ticket</a>
                     </li >
                     <li class="list-inline-item">
                         <a href="change_boarding.php">Change boarding point</a>
                     </li >
                                         <li class="list-inline-item">
                     <a href="cancellation_policy.php">Cancellation &amp; Refund policy</a>
                     </li>
                     <li class="list-inline-item">
                     <a href="privacy_policy.php">Privacy policy</a>
                     </li>
                     <li class="list-inline-item">
                         <a href="contact_us.php">Contact us</a>
                     </li>
</ul></div>
                </div>

        <div class="container-fluid">
            <div class="divider"></div>
        </div>
        <div class="container">
           
            <div class="row">
                <div class="col-md-6 text-center text-md-left mt-2  pt-2"> <img class="logo-invert" src="assets/logo.svg" alt="ART Travels">

                    <p>&copy; ART travels. All rights reserved. </p>
                    
                </div>
                <div class="col-md-6 text-center text-md-right mt-2 pt-2">
                
                    <p> Site designed and developed by <a target="_blank" href="http://selvam.co.in">selvam</a> </p> <small> Font generated by <a href="http://www.flaticon.com">flaticon.com</a>.  <p>Under <a href="http://creativecommons.org/licenses/by/3.0/">CC</a>: <a data-file="006-mp3" href="https://www.flaticon.com/authors/smashicons">Smashicons</a>, <a data-file="002-businessman" href="http://www.freepik.com">Freepik</a>, <a data-file="004-travel" href="https://www.flaticon.com/authors/google">Google</a>, <a data-file="001-business-woman" href="https://www.flaticon.com/authors/simpleicon">SimpleIcon</a></p>  
</small>
<a href="https://msg91.com/startups/?utm_source=startup-banner"><img src="https://msg91.com/images/startups/msg91Badge.png" width="120" height="90" title="MSG91 - SMS for Startups" alt="Bulk SMS - MSG91"></a>
                </div>
            </div>
        </div>
    </footer>
    <script src="js/jquery.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>